---
title: "Dry Age Log Analysis"
author: Tan Ho
date: "`r Sys.Date()`"
output:
  github_document:
  html_document:
    self_contained: true
---

Parameters
```{r parameters}
roll_minutes <- 30
```
Utils
```{r utils}
.dew_point <- function(temp_c, rh_pct) {
  stopifnot(length(temp_c) == length(rh_pct))
  a <- 17.625
  b <- 243.04

  x <- ((a * temp_c) / (b + temp_c)) + log(rh_pct / 100)

  return((b * x) / (a - x))
}
c_to_f <- function(temp_c) (temp_c * 9/5) + 32
f_to_c <- function(temp_f) (temp_f - 32) * 5/9
```
Data Pull
```{r data_pull}
system("scp tan@relicanth:/home/tan/dry_age_monitor/logs/* logs")
```

```{r parse}
readings <- list.files(path = "logs", full.names = TRUE) |>
  purrr::map(readLines) |>
  unlist() |>
  purrr::map(jsonlite::parse_json) |>
  tibble::tibble() |>
  tidyr::unnest_wider(1) |>
  dplyr::mutate(
    timestamp = lubridate::as_datetime(timestamp),
    temperature_f = c_to_f(temperature_c),
    dew_point = .dew_point(temperature_c, humidity_pct) |> c_to_f(),
    tempf_rollmean = slider::slide_dbl(
      temperature_f,
      mean,
      .before = 2 * roll_minutes
    ),
    tempf_rollmax = slider::slide_dbl(
      temperature_f,
      \(x) quantile(x, 0.95),
      .before = 2 * roll_minutes
    ),
    tempf_rollmin = slider::slide_dbl(
      temperature_f,
      \(x) quantile(x, 0.05),
      .before = 2 * roll_minutes
    ),
    humidity_rollmean = slider::slide_dbl(
      humidity_pct,
      mean,
      .before = 2 * roll_minutes
    ),
    humidity_rollmax = slider::slide_dbl(
      humidity_pct,
      \(x) quantile(x, 0.95),
      .before = 2 * roll_minutes
    ),
    humidity_rollmin = slider::slide_dbl(
      humidity_pct,
      \(x) quantile(x, 0.05),
      .before = 2 * roll_minutes
    ),
    dew_point_rollmean = slider::slide_dbl(
      dew_point,
      mean,
      .before = 2 * roll_minutes
    ),
    dew_point_rollmax = slider::slide_dbl(
      dew_point,
      \(x) quantile(x, 0.95),
      .before = 2 * roll_minutes
    ),
    dew_point_rollmin = slider::slide_dbl(
      dew_point,
      \(x) quantile(x, 0.05),
      .before = 2 * roll_minutes
    ),
    pressure_rollmean = slider::slide_dbl(
      pressure_hpa,
      mean,
      .before = 2 * roll_minutes
    ),
    pressure_rollmax = slider::slide_dbl(
      pressure_hpa,
      \(x) quantile(x, 0.95),
      .before = 2 * roll_minutes
    ),
    pressure_rollmin = slider::slide_dbl(
      pressure_hpa,
      \(x) quantile(x, 0.05),
      .before = 2 * roll_minutes
    ),
    gas_rollmean = slider::slide_dbl(
      gas_ohms,
      mean,
      .before = 2 * roll_minutes
    ),
    gas_rollmax = slider::slide_dbl(
      gas_ohms,
      \(x) quantile(x, 0.95),
      .before = 2 * roll_minutes
    ),
    gas_rollmin = slider::slide_dbl(
      gas_ohms,
      \(x) quantile(x, 0.05),
      .before = 2 * roll_minutes
    )
  )
```
Plots
```{r plot}
readings |>
  ggplot2::ggplot(ggplot2::aes(x = timestamp)) +
  ggplot2::geom_line(ggplot2::aes(y = tempf_rollmean)) +
  ggplot2::geom_point(
    ggplot2::aes(y = tempf_rollmax),
    size = 1,
    color = "lightblue"
  ) +
  ggplot2::geom_point(
    ggplot2::aes(y = tempf_rollmin),
    size = 1,
    color = "darkblue"
  ) +
  tantastic::theme_tantastic(base_size = 16, plot_title_size = 20) +
  ggplot2::scale_y_continuous(
    limits = c(NA, 48),
    minor_breaks = seq.int(
      min(readings$tempf_rollmin),
      max(readings$tempf_rollmax)
    )
  ) +
  ggplot2::scale_x_datetime(timezone = "America/Toronto") +
  ggplot2::labs(
    title = "Temperature",
    subtitle = glue::glue("Rolling mean of last {roll_minutes} minutes"),
    x = "Timestamp (America/Toronto)",
    y = "°F"
  )
readings |>
  ggplot2::ggplot(ggplot2::aes(x = timestamp)) +
  ggplot2::geom_line(ggplot2::aes(y = humidity_rollmean)) +
  ggplot2::geom_point(
    ggplot2::aes(y = humidity_rollmax),
    size = 1,
    color = "lightblue"
  ) +
  ggplot2::geom_point(
    ggplot2::aes(y = humidity_rollmin),
    size = 1,
    color = "darkblue"
  ) +
  tantastic::theme_tantastic(base_size = 16, plot_title_size = 20) +
  ggplot2::scale_y_continuous(
    minor_breaks = seq.int(
      min(readings$humidity_rollmin),
      max(readings$humidity_rollmax)
    )
  ) +
  ggplot2::scale_x_datetime(timezone = "America/Toronto") +
  ggplot2::labs(
    title = "Relative Humidity",
    subtitle = glue::glue("Rolling mean of last {roll_minutes} minutes"),
    x = "Timestamp (America/Toronto)",
    y = "%"
  )

readings |>
  ggplot2::ggplot(ggplot2::aes(x = timestamp)) +
  ggplot2::geom_point(ggplot2::aes(y = tempf_rollmean - dew_point_rollmean)) +
  ggplot2::geom_point(ggplot2::aes(y = tempf_rollmax - dew_point_rollmax), color = "lightblue") +
  ggplot2::geom_point(ggplot2::aes(y = tempf_rollmin - dew_point_rollmin), color = "darkblue") +
  tantastic::theme_tantastic(base_size = 16, plot_title_size = 20) +
  # ggplot2::scale_y_continuous(limits = c(-8, 8)) +
  ggplot2::scale_x_datetime(timezone = "America/Toronto") +
  ggplot2::labs(
    title = "Temperature Minus Dew Point",
    subtitle = glue::glue("Rolling mean of last {roll_minutes} minutes"),
    x = "Timestamp (America/Toronto)",
    y = "°F"
  )

readings |>
  ggplot2::ggplot(ggplot2::aes(x = timestamp)) +
  ggplot2::geom_point(ggplot2::aes(y = pressure_rollmean)) +
  ggplot2::geom_point(ggplot2::aes(y = pressure_rollmax), color = "lightblue") +
  ggplot2::geom_point(ggplot2::aes(y = pressure_rollmin), color = "darkblue") +
  tantastic::theme_tantastic(base_size = 16, plot_title_size = 20) +
  # ggplot2::scale_y_continuous(limits = c(-8, 8)) +
  ggplot2::scale_x_datetime(timezone = "America/Toronto") +
  ggplot2::labs(
    title = "Air Pressure",
    subtitle = glue::glue("Rolling mean of last {roll_minutes} minutes"),
    x = "Timestamp (America/Toronto)",
    y = "hPa"
  )

readings |>
  ggplot2::ggplot(ggplot2::aes(x = timestamp)) +
  ggplot2::geom_point(ggplot2::aes(y = gas_rollmean)) +
  ggplot2::geom_point(ggplot2::aes(y = gas_rollmax), color = "lightblue") +
  ggplot2::geom_point(ggplot2::aes(y = gas_rollmin), color = "darkblue") +
  tantastic::theme_tantastic(base_size = 16, plot_title_size = 20) +
  # ggplot2::scale_y_continuous(limits = c(-8, 8)) +
  ggplot2::scale_x_datetime(timezone = "America/Toronto") +
  ggplot2::labs(
    title = "Gas",
    subtitle = glue::glue("Rolling mean of last {roll_minutes} minutes"),
    x = "Timestamp (America/Toronto)",
    y = "Ohms"
  )
```
