---
title: "Dry Age Monitor - Log Analysis"
date: "`r Sys.time()`"
output:
  github_document:
    dev: ragg_png
    fig_width: 12
    fig_height: 8
  html_document:
    self_contained: true
    dev: ragg_png
    fig_width: 12
    fig_height: 8
---
```{r setup}
knitr::opts_chunk$set(echo = FALSE, dev = "ragg_png")
suppressPackageStartupMessages({
  library(jsonlite)
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(slider)
  library(lubridate)
  library(glue)
  library(ggplot2)
  library(geomtextpath)
  library(scales)
  library(ragg)
  library(marquee)
  library(tantastic)
  library(here)
})
here::i_am("reports/log_analysis.Rmd")
```
```{r parameters, echo = FALSE}
roll_minutes <- 60
start_date <- lubridate::as_datetime("2026-07-13 12:00:00 UTC")
end_date <- Sys.time()
events <- tibble::tribble(
  ~timestamp                                        , ~label                                  ,
  lubridate::as_datetime("2026-07-13 22:00:00 UTC") , "ribeye added to fridge"                ,
  lubridate::as_datetime("2026-07-14 22:00:00 UTC") , "initial monitor setup"                 ,
  lubridate::as_datetime("2026-07-15 17:15:00 UTC") , "usb fan installed vertically"          ,
  lubridate::as_datetime("2026-07-15 23:45:00 UTC") , "usb fan reinstalled horizontally"      ,
  lubridate::as_datetime("2026-07-16 02:40:00 UTC") , "add water jug, duct-tape cable-gaps"   ,
  lubridate::as_datetime("2026-07-16 19:20:00 UTC") , "more jugs, use case fan + foam tape"   ,
  lubridate::as_datetime("2026-07-17 01:15:00 UTC") , "reorient fan horizontally"             ,
  lubridate::as_datetime("2026-07-17 16:01:00 UTC") , "apply +0.5C calibration"               ,
  lubridate::as_datetime("2026-07-18 04:30:00 UTC") , "adjust fan orientation"                ,
  lubridate::as_datetime("2026-07-18 14:30:00 UTC") , "add salt tray, relocate to lower rack" ,
  lubridate::as_datetime("2026-07-19 19:00:00 UTC") , "add two more water jugs"               ,
  lubridate::as_datetime("2026-07-22 19:00:00 UTC") , "mess with fridge sensor"               ,
)
```

## dry age status

Current dry-age duration: `r round(end_date - start_date, 1)` days

Starting weight: 14.2 lbs

Start date: `r format(start_date, "%Y-%m-%d")`

Target date: `r format(start_date + lubridate::days(45), "%Y-%m-%d")` (45 days)

## event timeline
```{r event_timeline}
events |>
  dplyr::transmute(
    local_time = lubridate::with_tz(timestamp, "America/Toronto"),
    event = label
  ) |>
  knitr::kable()
```
```{r utils}
.dew_point <- function(temp_c, rh_pct) {
  stopifnot(length(temp_c) == length(rh_pct))
  a <- 17.625
  b <- 243.04

  x <- ((a * temp_c) / (b + temp_c)) + log(rh_pct / 100)

  return((b * x) / (a - x))
}
c_to_f <- function(temp_c) (temp_c * 9/5) + 32
f_to_c <- function(temp_f) (temp_f - 32) * 5/9
```

```{r parse}
readings <- list.files(path = here::here("logs"), full.names = TRUE) |>
  lapply(yyjsonr::read_ndjson_file) |>
  tibble::tibble() |>
  tidyr::unnest(1) |>
  dplyr::filter(timestamp >= start_date & timestamp <= end_date) |>
  dplyr::mutate(
    timestamp = lubridate::as_datetime(timestamp),
    temperature_f = c_to_f(temperature_c) |> round(2)
  )

rolling_metrics <- readings |>
  dplyr::select(
    timestamp,
    temperature_f,
    humidity_pct,
    gas_ohms,
    pressure_hpa
  ) |>
  tidyr::pivot_longer(
    -timestamp,
    names_to = "metric",
    values_to = "raw_value"
  ) |>
  dplyr::mutate(
    rollmean = slider::slide_index_dbl(
      .x = raw_value,
      .i = timestamp,
      .f = \(x) mean(x, na.rm = TRUE),
      .before = lubridate::minutes(roll_minutes)
    ),
    roll = slider::slide_index(
      .x = raw_value,
      .i = timestamp,
      .f = \(x) {
        quantile(x, c(0.05, 0.2, 0.8, 0.95), na.rm = TRUE) |>
          setNames(nm = c("roll05", "roll20", "roll80", "roll95"))
      },
      .before = lubridate::minutes(roll_minutes)
    ),
    .by = metric
  ) |>
  tidyr::unnest_wider(roll) |>
  tidyr::pivot_longer(
    cols = c("raw_value", starts_with("roll")),
    names_to = "metric_type",
    values_to = "value"
  ) |>
  dplyr::mutate(
    metric_type = forcats::fct_relevel(
      metric_type,
      "raw_value",
      "roll05",
      "roll20",
      "rollmean",
      "roll80",
      "roll95"
    )
  )
```

## Rolling Average Plots
```{r plot}
plot_rolling_metric <- function(
  metric_name,
  rolling_metrics,
  roll_minutes,
  plot_title = NULL,
  plot_subtitle = NULL,
  timestamp_limits = NULL,
  timestamp_reference_lines = NULL,
  metric_units = NULL,
  metric_breaks_width = 1,
  metric_limits = NULL,
  metric_reference_lines = NULL,
  metric_types = c("roll05", "roll20", "rollmean", "roll80", "roll95")
) {
  d <- rolling_metrics |>
    dplyr::filter(metric_name == metric, metric_type %in% metric_types)

  suppressWarnings({
    p <- ggplot(aes(x = timestamp, y = value), data = d) +
      purrr::compact(
        list(
          tantastic::theme_tantastic(
            base_size = 16,
            plot_title_size = 20,
            axis_title_size = 16,
            axis_text_size = 14,
            caption_size = 12
          ),
          geom_point(
            aes(y = value, color = metric_type),
            size = 0.2,
            alpha = 0.1
          ),
          if (!is.null(metric_reference_lines)) {
            geom_texthline(
              yintercept = metric_reference_lines$y,
              label = metric_reference_lines$label,
              color = "white",
              alpha = 0.8,
              hjust = 1,
              data = metric_reference_lines
            )
          },
          geom_smooth(
            aes(y = value, color = metric_type, label = metric_type),
            linewidth = 1,
            method = "gam",
            formula = y ~ s(x, bs = "cs", fx = TRUE, k = 100),
            alpha = 1,
            size = 0.5,
            n = 1000
          ),
          if (!is.null(timestamp_reference_lines)) {
            geom_labelvline(
              xintercept = timestamp_reference_lines$timestamp,
              label = timestamp_reference_lines$label,
              color = "white",
              fill = "white",
              textcolor = "black",
              label.r = unit(0.05, "lines"),
              label.padding = unit(0.05, "lines"),
              alpha = 0.8,
              hjust = 0.05,
              linewidth = 0.5,
              linetype = 2,
              data = timestamp_reference_lines
            )
          },
          scale_y_continuous(
            limits = metric_limits,
            expand = ggplot2::expansion(c(0.2, 0)),
            minor_breaks = scales::minor_breaks_width(metric_breaks_width, 0)
          ),
          scale_x_datetime(
            limits = timestamp_limits,
            expand = ggplot2::expansion(c(0.05, 0.1)),
            timezone = "America/Toronto"
          ),
          labs(
            title = plot_title,
            subtitle = plot_subtitle,
            caption = glue::glue(
              "Rolling metrics over last {roll_minutes} minutes"
            ),
            x = "Timestamp (America/Toronto)",
            y = metric_units
          ),
          theme(legend.position = "top")
        )
      )
  })
  return(p)
}

plot_rolling_metric(
  metric_name = "temperature_f",
  rolling_metrics = rolling_metrics,
  roll_minutes = roll_minutes,
  plot_title = "Temperature",
  plot_subtitle = "Canadians do cooking in Fahrenheit ;)",
  metric_units = "degrees F",
  metric_limits = c(28, 48),
  metric_reference_lines = data.frame(
    y = c(32, 34, 38, 40),
    label = c("freezing", "lower", "upper", "danger")
  ),
  timestamp_reference_lines = events
)

plot_rolling_metric(
  metric_name = "humidity_pct",
  rolling_metrics = rolling_metrics,
  roll_minutes = roll_minutes,
  plot_title = "Relative Humidity",
  plot_subtitle = "Percentage of theoretical maximum water vapor that can be held in the air at this temperature",
  metric_units = "Percent",
  timestamp_reference_lines = events,
  metric_limits = NULL,
  metric_reference_lines = data.frame(
    y = c(75, 85, 100),
    label = c("lower", "upper", "saturation")
  ),
)

plot_rolling_metric(
  metric_name = "gas_ohms",
  rolling_metrics = rolling_metrics,
  roll_minutes = roll_minutes,
  plot_title = "Gas Resistance",
  plot_subtitle = "Higher values indicate cleaner air = less offgassing",
  metric_units = "Ohms",
  timestamp_limits = NULL,
  timestamp_reference_lines = events,
  metric_limits = NULL,
  metric_breaks_width = 1000,
  metric_reference_lines = NULL
)

plot_rolling_metric(
  metric_name = "pressure_hpa",
  rolling_metrics = rolling_metrics,
  roll_minutes = roll_minutes,
  plot_title = "Air Pressure",
  plot_subtitle = "apparently just a weather thing? who knows.",
  metric_units = "hPa",
  timestamp_limits = NULL,
  timestamp_reference_lines = events,
  metric_breaks_width = 100,
  metric_limits = NULL,
  metric_reference_lines = NULL,
  metric_types = "rollmean"
)
```

## Summary Tables
```{r table}
table_rolling_metrics <- function(
  metric_name,
  n_digits = 2
) {
  roll_by <- if (roll_minutes > 60) {
    lubridate::minutes(60)
  } else {
    lubridate::minutes(roll_minutes)
  }

  rolling_metrics |>
    dplyr::filter(metric == metric_name, metric_type != "raw_value") |>
    dplyr::mutate(
      metric_type = forcats::fct_relevel(
        metric_type,
        "roll05",
        "roll20",
        "rollmean",
        "roll80",
        "roll95"
      ),
      value = round(value, n_digits)
    ) |>
    dplyr::arrange(metric_type) |>
    tidyr::pivot_wider(
      names_from = metric_type,
      values_from = value
    ) |>
    dplyr::mutate(
      timestamp = lubridate::floor_date(
        timestamp,
        unit = roll_by
      )
    ) |>
    dplyr::summarize(
      dplyr::across(everything(), \(x) mean(x, na.rm = TRUE) |> round(2)),
      .by = c(timestamp, metric)
    ) |>
    knitr::kable()
}

table_rolling_metrics("temperature_f", 1)
table_rolling_metrics("humidity_pct", 1)
table_rolling_metrics("gas_ohms", 0)
table_rolling_metrics("pressure_hpa", 0)
```

## Cycle Analysis
```{r cycle_metrics}
cycle_metrics <- readings |>
  dplyr::mutate(
    cycle_trend = ifelse(
      dplyr::lag(temperature_f, default = Inf) > temperature_f,
      "down",
      "up"
    ),
    cycle_num = dplyr::consecutive_id(cycle_trend)
  ) |>
  dplyr::mutate(
    cycle_duration = max(timestamp) - min(timestamp),
    .by = cycle_num
  ) |>
  # collapse cycles shorter than 90s with the previous cycle
dplyr::mutate(
  cycle_num = ifelse(cycle_duration <= lubridate::seconds(90), NA, cycle_num) |>
    vctrs::vec_fill_missing(direction = "down") |>
    dplyr::consecutive_id(),
  cycle_trend = ifelse(cycle_duration <= lubridate::seconds(90), NA, cycle_trend) |>
    vctrs::vec_fill_missing(direction = "down")
) |>
  dplyr::mutate(
    cycle_start_time = min(timestamp),
    cycle_end_time = max(timestamp),
    cycle_duration = max(timestamp) - min(timestamp),
    .by = cycle_num
  ) |>
  dplyr::select(
    cycle_num,
    cycle_trend,
    starts_with("cycle"),
    temperature_f,
    humidity_pct,
    gas_ohms,
    pressure_hpa
  ) |>
  tidyr::pivot_longer(
    -starts_with("cycle"),
    names_to = "metric",
    values_to = "raw_value"
  ) |>
  dplyr::summarise(
    .by = c(starts_with("cycle"), "metric"),
    mean = mean(raw_value, na.rm = TRUE),
    quantiles = quantile(
      raw_value,
      c(0.05, 0.20, 0.8, 0.95),
      na.rm = TRUE
    ) |>
      round(2) |>
      setNames(c("p05", "p20", "p80", "p95")) |>
      as.list() |>
      list()
  ) |>
  tidyr::unnest_wider(quantiles) |>
  tidyr::pivot_wider(
    names_from = metric,
    values_from = c(mean, starts_with("p")),
    names_glue = "{metric}_{.value}",
    names_vary = "slowest"
  )
```

```{r}
table_cycle_metrics <- function(
  metric_name,
  n_digits = 2
) {
  cycle_metrics |>
    dplyr::select(
      starts_with("cycle"),
      starts_with(metric_name)
    ) |>
    dplyr::mutate(
      across(starts_with(metric_name), \(x) round(x, 2))
    ) |>
    dplyr::rename_all(\(x) gsub(paste0(metric_name, "_"), "", x)) |>
    knitr::kable()
}
table_cycle_metrics("temperature_f", 1)
table_cycle_metrics("humidity_pct", 1)
table_cycle_metrics("gas_ohms", 0)
table_cycle_metrics("pressure_hpa", 0)
```
